const express = require("express");
const router = express.Router();
const authRoutes = require("./authRoutes");
const userProfileRoutes = require("./userProfileRoutes");
const productRoutes = require("./productRoutes");
const wishlistRoutes = require("./wishlistRoutes");
const brandRoutes = require("./brandRoutes");
const cartRoutes = require("./cartRoutes");
const reviewRoutes = require("./reviewRoutes");
const taxesRoutes = require("./taxesRoutes");
const returnPolicyRoutes = require("./returnPolicyRoutes");
const categoryRoutes = require("./categoryRoutes");
const userManagementRoutes = require("./userManagementRoutes");
const marketingMngRoutes = require("./marketingMngRoutes");
const vendorRoutes = require("./vendorRoutes");
const roleMngRoutes = require("./roleMngRoutes");
const serviceIntegrationRoutes = require("./serviceIntegrationRoutes");
const shopifyMngRoutes = require("./shopifyMngRoutes");
const warehouseRoutes = require("./warehouseRoutes");
const blogRoutes = require("./blogRoutes");
const orderMngRoutes = require("./orderMngRoutes");

router.get("/", (req, res) => {
  res.send("Welcome to la-fetch backend");
});
router.use("/auth", authRoutes);
router.use("/profile", userProfileRoutes);
router.use("/", productRoutes);
router.use("/", wishlistRoutes);
router.use("/", brandRoutes);
router.use("/", cartRoutes);
router.use("/", reviewRoutes);
router.use("/", taxesRoutes);
router.use("/", returnPolicyRoutes);
router.use("/", categoryRoutes);
router.use("/", userManagementRoutes);
router.use("/", marketingMngRoutes);
router.use("/", vendorRoutes);
router.use("/", roleMngRoutes);
router.use("/", serviceIntegrationRoutes);
router.use("/", shopifyMngRoutes);
router.use("/", warehouseRoutes);
router.use("/", blogRoutes);
router.use("/", orderMngRoutes);

module.exports = router;
